### PR TITLE
Specification update: describe endpoints and generic informal architecture

### PR DESCRIPTION
**Pull request by koriaf**
Based on swagger and current implementations on testpoint
Fulfils basic needs of anyone getting information about the business, getting private keys, service metadatas and so on.
Please feel free to discuss, comment or just merge and make your changes if you see something incorrect.

There are not data format described yet, It's quite a time-consuming and boring work, but shall be done anyway (in further pull requests). I think JSON format shall stick to the OASIS XML, duplicating it, but extend it when it's required. We have to keep in mind backward compatibility to OASIS XML, so if European service eventually queries our DCL it's able to get at least service metadata information and get some endpoint.

### CODE REVIEW

**Comment by monkeypants** [comment]
I think this restores OASIS backwards compatibility, that was a bug (thanks).

I really like the `/{participant urn}/aka` extension resource. That's a really neat solution to identity linking (e.g. multiple GLNs belonging to a single ABN).

**Comment by MohsinJaffer** [comment]
I am new to this, however if this means a single AKA (end-point) represents all possible IDs i.e. ABN, GLNs, DUNs and potentially even the unregistered ID (buyer assigned identifiers) and these are all linked to one end point - If yes , then this is truly a brilliant solution !

**Comment by monkeypants** [comment]
Extending an OASIS backwards-compatible interface with new methods is a better principle than having oasis-similar interfaces. We started that pattern with the urn/keys method (collection of public keys used to identify the participant). Back-porting that change to compound identities is a definite improvement.

The reason it's not merged already is that it can't work without a change to the  IDP spec. Currently, we have identity claims in our JWt that have ID scheme as the key, and identifier as the value. To PUT or PATCH the urn/aka resource, you must be authenticated as all the identity claims. With the current scheme=key data structure, it's not possible to manage multiple identifiers with the same scheme (e.g. GLN).

So, we also need an update to the IDP spec with a different data structure in the JWT. For example, have one key for all of iso6523 identifiers, with a value that is a list of (scheme=identifier) dictionaries. 

We might also need a structure of unregistered identifiers too, but they are slightly more complicated again (because I think the DCP would need to know how to validate them, and the IDP would need to know how to verify them,, so they can't quite be treated as "free text")

Also, I think we should consider: should aka identity associations have temporal scope (like keys do, published and revoked)? Should that be the same aka method or an optional extra method?

**Comment by MohsinJaffer** [comment]
Some food for thought, thanks! I was having a look at the GS1 structure and thinking it might be a start to see the GLN Rules work - at present there is a way to define GTINs as parent, child, grandchild or GLNs in EDI based on Internal and External Interfaces (http://www.gs1.org/1/glnrules/en/overview) and to make matters more interesting,  how are a company's uniquely identified Dev, Test and Prod connections defined or would this be defined at a different level ?

**Comment by MohsinJaffer** [comment]
By the way in terms of multiple schemes with the same GLN is possibly not possible as GLNs (and GTINs) are unique and very specific by nature and any slight change or difference requires allocation of a new GLN (plus retaining the value of previous GLN for a period which can be up to 48 months or so and then should expire).

**Comment by monkeypants** [comment]
by multiple schemes, I meant that a business may have an ABN (one scheme) plus some GLNs (another scheme). They might have identifiers from multiple ISO 6523 schemes, and even perhaps `urn:oasis:names:tc:ebcore:partyid-type:iso20022:ProprietaryIdentification:yourclientcomain.com::12345` (?)

**Comment by MohsinJaffer** [comment]
Got it, then in that case the end point for healthcare is generally one scheme "GS1" other industries such ash FMCG (Coles , Woolies etc), Office Supplies, liquor and hardware use GLN too however surely there will be other schemes and may have impact for other sectors that use other identifiers for different areas of their business too. How does PEPPOL handle this I wonder

**Pull request merged**
